/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEVICE_ACCESS 1

#define IBM_VPD 0

#define INPUT_HISTORY_BUSNAME_ROOT "org.open_power.powersupply"

#define INPUT_HISTORY_SENSOR_ROOT "/org/open_power/sensors/aggregation/per_30s"

#define PSU_JSON_PATH "/usr/share/phosphor-power/psu.json"

#define SEQUENCER UCD90160

